"""
biscotti._scaffolds
~~~~~~~~~~~~~~~~~~~
Provider-specific app.py templates generated by `biscotti dev`.
"""
from __future__ import annotations

PROVIDERS = ("anthropic", "openai", "pydanticai", "other")

_DEFAULT_SYSTEM_PROMPT = "You are a helpful assistant."

_ANTHROPIC = '''\
import anthropic
from contextlib import asynccontextmanager
from fastapi import FastAPI
from biscotti import Biscotti, biscotti

client = anthropic.AsyncAnthropic()


@biscotti(
    name="{name}",
    default_system_prompt="{system_prompt}",
)
async def {fn}(user_message: str, system_prompt: str) -> dict:
    response = await client.messages.create(
        model="{model}",
        max_tokens=1024,
        system=system_prompt,
        messages=[{{"role": "user", "content": user_message}}],
    )
    return {{
        "output": response.content[0].text,
        "input_tokens": response.usage.input_tokens,
        "output_tokens": response.usage.output_tokens,
        "model": response.model,
    }}


bi = Biscotti(storage="sqlite:///biscotti.db")


@asynccontextmanager
async def lifespan(app: FastAPI):
    yield


app = FastAPI(lifespan=lifespan)
app.mount("/biscotti", bi.app)
'''

_OPENAI = '''\
from contextlib import asynccontextmanager
from fastapi import FastAPI
from openai import AsyncOpenAI
from biscotti import Biscotti, biscotti

client = AsyncOpenAI()


@biscotti(
    name="{name}",
    default_system_prompt="{system_prompt}",
)
async def {fn}(user_message: str, system_prompt: str) -> dict:
    response = await client.chat.completions.create(
        model="{model}",
        messages=[
            {{"role": "system", "content": system_prompt}},
            {{"role": "user", "content": user_message}},
        ],
    )
    return {{
        "output": response.choices[0].message.content,
        "input_tokens": response.usage.prompt_tokens,
        "output_tokens": response.usage.completion_tokens,
        "model": response.model,
    }}


bi = Biscotti(storage="sqlite:///biscotti.db")


@asynccontextmanager
async def lifespan(app: FastAPI):
    yield


app = FastAPI(lifespan=lifespan)
app.mount("/biscotti", bi.app)
'''

_PYDANTICAI = '''\
from contextlib import asynccontextmanager
from fastapi import FastAPI
from pydantic_ai import Agent
from biscotti import Biscotti, biscotti

_agent = Agent(model="{model}")


@biscotti(
    name="{name}",
    default_system_prompt="{system_prompt}",
)
async def {fn}(user_message: str, system_prompt: str) -> str:
    result = await _agent.run(user_message, system_prompt=system_prompt)
    return result.output


bi = Biscotti(storage="sqlite:///biscotti.db")


@asynccontextmanager
async def lifespan(app: FastAPI):
    yield


app = FastAPI(lifespan=lifespan)
app.mount("/biscotti", bi.app)
'''

_OTHER = '''\
from contextlib import asynccontextmanager
from fastapi import FastAPI
from biscotti import Biscotti, biscotti


@biscotti(
    name="{name}",
    default_system_prompt="{system_prompt}",
)
async def {fn}(user_message: str, system_prompt: str) -> str:
    # TODO: call your model here and return the response as a string.
    # See the README for examples using Anthropic, OpenAI, PydanticAI, and others.
    raise NotImplementedError("Connect your model here")


bi = Biscotti(storage="sqlite:///biscotti.db")


@asynccontextmanager
async def lifespan(app: FastAPI):
    yield


app = FastAPI(lifespan=lifespan)
app.mount("/biscotti", bi.app)
'''

_TEMPLATES = {
    "anthropic": _ANTHROPIC,
    "openai": _OPENAI,
    "pydanticai": _PYDANTICAI,
    "other": _OTHER,
}


def _snake(name: str) -> str:
    """'My Cool Agent' -> 'my_cool_agent'"""
    return name.strip().lower().replace(" ", "_").replace("-", "_")


def render_scaffold(provider: str, *, agent_name: str, model: str) -> str:
    """Return a complete app.py string for the given provider."""
    if provider not in _TEMPLATES:
        raise ValueError(
            f"Unknown provider: {provider!r}. Choose from: {', '.join(PROVIDERS)}"
        )
    return _TEMPLATES[provider].format(
        name=agent_name,
        fn=_snake(agent_name),
        model=model,
        system_prompt=_DEFAULT_SYSTEM_PROMPT,
    )
